import os
import torch
import tempfile
import uvicorn
from fastapi import FastAPI, UploadFile, File, Form, BackgroundTasks
from fastapi.responses import FileResponse
from TTS.api import TTS

app = FastAPI(title="PhaseGuard Voice Cloning API", description="XTTSv2 GPU Server for Scambaiter")

# Load Model globally on GPU
# We use XTTS-v2 because it only needs a 3-second reference audio to clone a voice perfectly.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Loading XTTSv2 model on {device}...")

# Fix Matplotlib GUI crash
os.environ['MPLBACKEND'] = 'Agg'
# Bypass Coqui TOS interactive prompt
import TTS.utils.manage
def mock_ask_tos(path): return True
TTS.utils.manage.ask_tos = mock_ask_tos

tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2").to(device)
print("Model loaded successfully!")

@app.post("/clone_voice")
async def clone_voice(
    text: str = Form(..., description="The text the AI should speak"),
    reference_audio: UploadFile = File(..., description="The 3+ second audio of the user's real voice")
):
    """
    Takes the text generated by Groq (Scambaiter) and the User's voice sample,
    and returns the synthesized audio in the user's exact voice.
    """
    # Save the uploaded reference audio to a temporary file
    with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as temp_ref:
        temp_ref.write(await reference_audio.read())
        ref_path = temp_ref.name

    # Create a temporary file for the output
    output_path = tempfile.mktemp(suffix=".wav")

    try:
        # Generate the voice clone!
        tts.tts_to_file(
            text=text,
            speaker_wav=ref_path,
            language="en", # You can dynamically change this to 'hi' for Hindi
            file_path=output_path
        )
        
        # Return the generated audio file
        return FileResponse(
            output_path, 
            media_type="audio/wav", 
            filename="scambaiter_reply.wav",
            background=BackgroundTasks().add_task(os.remove, ref_path) # Cleanup temp ref file
        )

    except Exception as e:
        if os.path.exists(ref_path):
            os.remove(ref_path)
        return {"status": "error", "message": str(e)}

if __name__ == "__main__":
    # Camber usually exposes port 8000
    uvicorn.run(app, host="0.0.0.0", port=8000)
