"""
escalation/whatsapp_escalation.py — Send cybercrime escalation via WhatsApp Business API.

Uses the existing WHATSAPP_ACCESS_TOKEN and WHATSAPP_PHONE_NUMBER_ID from .env.
Sends a structured message to the FAMILY_CONTACT_NUMBER (configured in .env)
so the victim's family / trusted contact immediately knows a scam was detected.
"""

from __future__ import annotations

import logging
import os
from typing import Any

import httpx

logger = logging.getLogger(__name__)

GRAPH_API_URL = "https://graph.facebook.com/v19.0"


async def send_whatsapp_escalation_alert(
    call_id: str,
    verdict: str,
    upi_ids: list[str],
    phone_numbers: list[str],
    entities: list[str],
    audio_hash: str,
) -> dict[str, Any]:
    """
    Send a structured WhatsApp alert to the configured contact number.

    Returns a dict with success status and any error.
    """
    token = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
    phone_number_id = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
    to_number = os.getenv("FAMILY_CONTACT_NUMBER", "").replace("+", "")

    if not token or not phone_number_id or not to_number:
        logger.warning(
            "WhatsApp escalation skipped — WHATSAPP_ACCESS_TOKEN, "
            "WHATSAPP_PHONE_NUMBER_ID, or FAMILY_CONTACT_NUMBER not configured."
        )
        return {
            "success": False,
            "error": "WhatsApp credentials not configured",
            "delivery_status": "WHATSAPP_NOT_CONFIGURED",
        }

    upi_text = ", ".join(upi_ids) if upi_ids else "None detected"
    phones_text = ", ".join(phone_numbers) if phone_numbers else "None"
    entities_text = ", ".join(entities) if entities else "None"

    message_body = (
        f"🛡 *PhaseGuard SCAM ALERT* 🛡\n\n"
        f"A *{verdict}* scam call was intercepted on your family member's phone.\n\n"
        f"📋 *Evidence Summary:*\n"
        f"• Call ID: `{call_id[:12]}...`\n"
        f"• Verdict: *{verdict}*\n"
        f"• UPI IDs detected: {upi_text}\n"
        f"• Phone numbers: {phones_text}\n"
        f"• Impersonated: {entities_text}\n"
        f"• Audio SHA-256: `{audio_hash[:16]}...`\n\n"
        f"⚠️ *Do NOT transfer any money!*\n\n"
        f"📞 Report at:\n"
        f"• Cybercrime Portal: https://cybercrime.gov.in\n"
        f"• Helpline: *1930* (toll-free, 24x7)\n\n"
        f"_Generated by PhaseGuard Anti-Scam OS_"
    )

    payload = {
        "messaging_product": "whatsapp",
        "recipient_type": "individual",
        "to": to_number,
        "type": "text",
        "text": {
            "preview_url": False,
            "body": message_body,
        },
    }

    url = f"{GRAPH_API_URL}/{phone_number_id}/messages"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }

    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(url, json=payload, headers=headers)
            resp.raise_for_status()
            data = resp.json()
            msg_id = data.get("messages", [{}])[0].get("id", "unknown")
            logger.info(
                "WhatsApp escalation sent: call_id=%r msg_id=%r to=%r",
                call_id, msg_id, to_number,
            )
            return {
                "success": True,
                "message_id": msg_id,
                "delivery_status": f"WHATSAPP_SENT_{resp.status_code}",
                "error": None,
            }
    except httpx.HTTPStatusError as e:
        logger.error("WhatsApp escalation HTTP error: %s — %s", e, e.response.text[:200])
        return {
            "success": False,
            "error": f"HTTP {e.response.status_code}: {e.response.text[:100]}",
            "delivery_status": "WHATSAPP_HTTP_ERROR",
        }
    except Exception as e:
        logger.error("WhatsApp escalation failed: %s", e)
        return {
            "success": False,
            "error": str(e),
            "delivery_status": "WHATSAPP_ERROR",
        }
